spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://192.168.0.229:3306/cms?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&=false
        username: root
        password: pzIF01jQfcdiFVlE
      second:  #数据源2
        url: jdbc:mysql://192.168.0.229:3306/cms?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&=false
        username: root
        password: pzIF01jQfcdiFVlE
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      remove-abandoned: false
redis:
  maxTotal: 30
  maxIdle: 10
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: 1800000
  softMinEvictableIdleTimeMillis: 10000
  maxWaitMillis: 1500
  testOnBorrow: true
  testWhileIdle: true
  blockWhenExhausted: false
  Cluster:
    host: 192.168.0.105
    port: 6379
    host1: 192.168.0.105
    port1: 6380
    host2: 192.168.0.44
    port2: 6379
    host3: 192.168.0.44
    port3: 6380
    host4: 192.168.0.198
    port4: 6379
    host5: 192.168.0.198
    port5: 6380
rocket:
  nameServer: 192.168.0.133:9876;192.168.0.165:9876;192.168.0.40:9876
  basePackage: com.chinaventure
localUrl: /image/
esUrl:  https://esdata.chinaventure.com.cn/cv-sensitive/api/sensitive/internally/check
abstractUrl: http://192.168.0.196/cv-tokenizer/lexer
redisUrl: http://192.168.0.52
newsUrl: /cms/api/updateNewsDetail
channelUrl: /cms/api/updateChannelList
subjectUrl: /cms/api/updateSubject
columnUrl: /cms/api/updateColumn
mediaUrl: /cms/api/updateSsoMedia
pictureUrl: /cms/api/updatePictureList
focusUrl: /cms/api/updateFocusDetail
flashUrl: /cms/api/updateFlashDetail
reportUrl: /cms/api/updateReportDetail
recommendUrl: /cms/api/updateRecommendNewsList
dictUrl: /cms/api/updateSysDict
pvUrl: /cms/api/getAllPageView
channelNewsList: /cms/api/updateChannelNewsList
subjectNewsList: /cms/api/updateSubjectNewsList
pvRedisUrl: /cms/api/updateCountNewsList
versionUrl: /cms/api/updateAppVersion
endPoint: https://obs.cn-north-1.myhuaweicloud.com
ak: 2FBSHRRFZ5YLE3VPBMDK
sk: vqYIdh3xmKfjlhcM0qEwCeuY8QfRKHYnGYHWoDBx
local: cn-north-1
bucketName: chinaventure-static
baiduUrl: http://data.zz.baidu.com/urls?site=https://www.chinaventure.com.cn&token=EAN4cqLpc6TbSSFO
cvinfoUrl: https://www.chinaventure.com.cn
cvinfoMUrl: https://m.chinaventure.com.cn
baiduToken: EAN4cqLpc6TbSSFO
